spring.application.name=emotionmusic


spring.datasource.url=jdbc:postgresql://localhost:5432/emovibes
spring.datasource.username=postgres
spring.datasource.password=1010
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-simple.sql



spotify.client-id=2022979b2ff6488197685ed3aafe885b
spotify.client-secret=398f9c15ba584b02b65e36a71a86bfdc
spotify.token-url=https://accounts.spotify.com/api/token
spotify.api-base=https://api.spotify.com/v1